services:
  mcp:
    build:
      context: .
      dockerfile: docker/mcp.Dockerfile
    container_name: mcp-langgraph-server
    environment:
      - OPENAI_API_KEY
      - CHAT_MODEL
      - EMBEDDING_MODEL
      - INDEX_DIR=/app/app/data/index
      - DOCS_DIR=/app/app/data/docs
    volumes:
      - ./app/data:/app/app/data
    ports:
      - "8765:8765"
    command: ["python", "-m", "app.mcp_server"]
    restart: unless-stopped

  ingest:
    build:
      context: .
      dockerfile: docker/ingest.Dockerfile
    container_name: mcp-langgraph-ingest
    environment:
      - OPENAI_API_KEY
      - CHAT_MODEL
      - EMBEDDING_MODEL
      - INDEX_DIR=/app/app/data/index
      - DOCS_DIR=/app/app/data/docs
    volumes:
      - ./app/data:/app/app/data
    command: ["python", "-m", "scripts.build_index"]
    restart: "no"
    profiles: ["ingest"]
